# create a dev conda environment with: `make create_env` or `conda env create -f environment.yml`
name: pyoviz
channels:
  - conda-forge
dependencies:
  - python
  - pyomeca
  - vtk
  - pyqt
  - casadi
  - rbdl=*=*casadi*
  - biorbd=*=*casadi*
  - packaging
